### ISSUE TITLE
V2?

### ISSUE THREAD

**Issue by uat230214** [ryangriggs/PDFEncrypt#10]
Nice tool, but home website should tell the user that the password is the viewer password and not the owner password, and that the owner password is created on the fly and not shared with the user.

So, decryption is not possible ... I am now trapped with the the encrypted pdf having deleted the non encrypted ones.
Printing is not an option... as printing was blocked.
Now I will have to look for dark side tools to remove an unknown owner password...

Supposedly there was going to be published a V2, but probably will not be able to decrypt previously encrypted files with V1 ...

By the way, where is V2?

**Comment by uat230214** [comment]
Just for those in need ...

https://www.ilovepdf.com/unlock_pdf

Requests the viewer password then unlocks and removes the owner password

Heard that there are sites that do not even ask for the viewer password. Not my need.

This fact does not reduce PDFEncrypt value, just sets clearly the expectatives. In PDF, owner password protection is weak if you know the viewer password.
Note that I am not implying that not knowing the viewer password protects the document.

**Comment by ryangriggs** [comment]
You are absolutely correct that either password can be used to access the full PDF and that the permissions are easy to bypass.  
Many PDF viewers do not enforce permissions; for example Firefox PDF viewer or QPDF. Just open the file in Firefox, then print to a new PDF using the Windows PDF printer.  Voila, you have a new non-encrypted file with no passwords set.  However, this does not imply that encrypted PDFs are weak.  The document itself is protected with industry-standard encryption, and you must know at least one of the passwords to access the file or you're faced with cracking AES-256 encryption (providing you encrypted the file using the best option).

I have provided a modified version of PDFEncrypt V1 on the Github repo that allows specification of owner password.

V2 is not out yet because I have a more-than-full-time job. :)

**Comment by uat230214** [comment]
@ryangriggs 
thanks!
I did not try to be pushy although reading back might have sound that way. Just as I understood that it was ready i wondered I was unable to find it. That is the reason for the "where".
