### ISSUE TITLE
Maximum password length is 32 characters

### ISSUE THREAD

**Issue by mjarosie** [ryangriggs/PDFEncrypt#4]
Is [this](https://github.com/ryangriggs/PDFEncrypt/blob/475177c6e28a65e906b3a474731f13785a99f723/frmMain.Designer.cs#L194) caused by any technical limitations? Ideally I'd be able to provide a password of any length.

**Comment by mjarosie** [comment]
I just checked, [iText SDK](https://api.itextpdf.com/iText7/dotnet/7.1.8/classi_text_1_1_kernel_1_1_pdf_1_1_writer_properties.html#a38ea303765616b85be0ad72f47944e87) doesn't seem to enforce this.

**Comment by ryangriggs** [comment]
According to the below links, the PDF standard limits password length to 32 characters and ignores any subsequent characters. That's why I limited the password in this box.
Please see
[This](http://what-when-how.com/itext-5/encrypting-a-pdf-document-itext-5/)
and
[This](https://superuser.com/questions/821187/what-is-the-maximum-length-of-a-pdf-document-password)

I would be glad to be corrected on this point, but if the PDF standard only supports up to 32 chars, let's keep it that way in PDFEncrypt also, to avoid confusion.

**Comment by mjarosie** [comment]
It does take the first 32 characters into account, but allows longer passphrases. I'm certain it works as I've just encrypted a few dozens of pdfs with a passphrase longer than 32 characters using this version of the code, and I'm able to decrypt those files with no issues.

In my case - I wanted to use a long but easy to remember passphrase from password generator.

How about displaying a message somewhere on the side saying that only the first 32 characters will be taken into account when the given password is longer than 32 characters?

**Comment by ryangriggs** [comment]
Would this lead to a false sense of security if the user is allowed to enter more characters than are actually used in the encryption process?  I suppose we could show a message if the user enters more than 32 chars, stating that "any characters exceeding 32 will be ignored".  Which way would yield a more accurate experience?

**Comment by mjarosie** [comment]
I'd say this sort of a message displayed would be the best option. It makes sure there's no false sense of security as you mentioned, at the same time it's more flexible, especially as technically nothing should really prevent you from using a longer password if you want to.
